# Generated by Django 4.2.18 on 2025-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_tokenprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_id", models.CharField(max_length=100)),
                ("price_data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.RenameIndex(
            model_name="tokenprice",
            new_name="agents_toke_token_i_7c1eeb_idx",
            old_name="token_id_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenprice",
            new_name="agents_toke_timesta_7d9ce5_idx",
            old_name="timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenprice",
            new_name="agents_toke_token_i_645eec_idx",
            old_name="token_time_idx",
        ),
        migrations.AddField(
            model_name="tokenprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tokenprice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="pricecache",
            index=models.Index(
                fields=["token_id"], name="agents_pric_token_i_ec3ab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricecache",
            index=models.Index(
                fields=["expires_at"], name="agents_pric_expires_8799b7_idx"
            ),
        ),
    ]
